name: Tester

on:
  push:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v3
      
      - name: Setup npm
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Download truffle suite
        run: |
          npm install truffle -g

      - name: Test contract
        run: |
          truffle test
